resources:
  - name: jfrogCliGit
    type: GitRepo
    configuration:
      path: yahavi/jfrog-cli
      gitProvider: github
      buildOn:
        pullRequestCreate: true

pipelines:
  # Global configuration
  - name: TestCLI
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: yahavi/build-integration-env
            tag: latest
      environmentVariables:
        readOnly:
          GOPROXY: https://gocenter.io

    steps:
      # Artifactory tests
      - name: Artifactory
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - curl -X POST -u $int_jfrog_rt_user:int_jfrog_rt_password ${int_jfrog_rt_url}/api/security/token -d 'username=yahavi' -d 'expires_in=1800' | jq '.access_token' -r > token
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.artifactory -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.accessToken=$(\< token)
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"

      # Bintray tests
      - name: Bintray
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.bintray -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password -bt.user=$int_jfrog_bintray_user -bt.key=$int_jfrog_bintray_apikey
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"

      # Npm tests
      - name: Npm
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - npm --version
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.npm -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"

      # Maven tests
      - name: Maven
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - mvn --version
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.maven -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"

      # Gradle tests
      - name: Gradle
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - gradle --version
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.gradle -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"

      # Go tests
      - name: Go
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - go version
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.go -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"
    
      # Pip tests
      - name: Pip
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - pip --version
            - python -m venv .venv
            - source .venv/bin/activate
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.pip -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"
      
      # Distribution tests
      - name: Distribution
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.distribution -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password -rt.distUrl=$int_jfrog_dist_url
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"

      # NuGet tests
      - name: NuGet
        type: Bash
        configuration:
          integrations:
            - name: jfrog
          inputResources:
            - name: jfrogCliGit
        execution:
          onExecute:
            - update_commit_status jfrogCliGit --context "$step_name"
            - cd $res_jfrogCliGit_resourcePath
            - nuget help 2>&1 | head -1
            - apt install -yq dotnet-sdk-2.1
            - go test -v github.com/jfrog/jfrog-cli -timeout 0 -test.nuget -rt.url=$int_jfrog_rt_url -rt.user=$int_jfrog_rt_user -rt.password=$int_jfrog_rt_password
          onComplete:
            - update_commit_status jfrogCliGit --context "$step_name"