version: 1
type: maven

resolver:
    releaseRepo: ${MAVEN_REMOTE_REPO}
    snapshotRepo: ${MAVEN_REMOTE_REPO}
    username: ${RT_USERNAME}
    password: ${RT_PASSWORD}
    url: ${RT_URL}
deployer:
    releaseRepo: ${MAVEN_REPO1}
    snapshotRepo: ${MAVEN_REPO1}
    username: ${RT_USERNAME}
    password: ${RT_PASSWORD}
    url: ${RT_URL}